/* Site data — bilingual copy + therapies + (homepage) news fallback. */

window.SITE_DATA = {
  copy: {
    fr: {
      nav: [
        { label: "Mission", href: "#mission" },
        { label: "Marc", href: "#marc" },
        { label: "Thérapies", href: "#therapies" },
        { label: "Actualités", href: "#news" },
        { label: "Adhésion", href: "#join" }
      ],
      donate: "Faire un don",
      eyebrow_hero: "Association loi 1901 · Depuis 2023",
      hero_kicker: "Ma Rééducation",
      hero_title: "Collective.",
      hero_lede: "Donner aux enfants cérébrolésés — comme Marc — l'accès aux protocoles de rééducation les plus innovants du monde.",
      hero_meta: ["10 pays explorés", "27 protocoles documentés", "1 mère qui n'abandonne pas"],
      cta_primary: "Soutenir Marc",
      cta_secondary: "Lire l'histoire",
      portrait_name: "Marc, 14 ans",
      portrait_role: "Survivant, fils, futur YouTubeur",
      stat_unit: "min",
      stat_lbl: "Le temps avant que son cœur ne reparte. Toute notre histoire commence là.",
      mission_eyebrow: "Notre mission",
      mission_title: "Aucun parent ne devrait avoir à chercher seul.",
      mission_body: "Quand Marc a fait un arrêt cardiaque à 4 ans, sa mère a parcouru le monde — Espagne, Pologne, Israël, Russie, USA — pour trouver les thérapies qui n'existent pas encore en France. Aujourd'hui, l'association partage ces ressources, négocie des stages, organise des conférences avec chercheurs et cliniciens, et accompagne d'autres familles sur le même chemin.",
      pillars: [
        { n: "01", t: "Recherche & veille", d: "Une cartographie vivante des thérapies neuro-réhabilitatives à travers le monde — neuromodulation, cellules souches, oxygénothérapie, SPML, photobiomodulation." },
        { n: "02", t: "Stages intensifs", d: "Organisation de séjours de rééducation dans nos locaux ou en partenariat avec des cliniques à l'étranger, à des prix négociés." },
        { n: "03", t: "Conférences", d: "Live Zoom et chaîne YouTube avec les inventeurs et chercheurs : Yuri Danilov, BE Alink, Marco Gostoli, Manny Medina." }
      ],
      story_eyebrow: "Histoire de Marc",
      story_title: "Le 9 janvier 2016, Marc s'effondre dans une aire de jeux.",
      story_lede: "Il a 4 ans. Il est découvert quinze à vingt minutes plus tard. Les parents, le personnel, les militaires de la force Sentinelle, puis les pompiers, prodiguent un massage cardiaque jusqu'à ce que son cœur reparte.",
      story_chapters: [
        { y: "2016", t: "L'arrêt", d: "CHU de Grenoble. Déchocage, soins intensifs, MPR. Hospitalisé jusqu'en mai." },
        { y: "2016–2019", t: "Le cœur", d: "Cinq opérations cardiaques pour soigner le syndrome Wolff-Parkinson-White. La dernière à Milan." },
        { y: "2017→", t: "Le tour du monde", d: "Espagne, Pologne, Allemagne, Bulgarie, Israël, Russie, USA. À chaque pays, un protocole." },
        { y: "Aujourd'hui", t: "6ᵉ ULIS", d: "Marc est en classe de 6ᵉ avec une AESH. Il veut être YouTubeur. Il a rencontré FuzeIII en avril 2026." }
      ],
      story_pull: "« Au jour de ta naissance, le monde est devenu plus coloré et plus gentil. »",
      story_pull_attr: "— sa maman, pour son anniversaire",
      story_photo_cap: "Une mère, son fils — le commencement de tout.",
      book_title: "Marc<br>l'Invincible",
      book_author: "Svetlana Serigny",
      book_eyebrow: "Le livre",
      book_h: "Son histoire, racontée par sa mère.",
      book_body: "Combats, doutes, persévérance — le témoignage d'un amour inconditionnel. Disponible en français et en anglais, papier et numérique.",
      therapies_eyebrow: "Thérapies documentées",
      therapies_title: "Ce que la France ne propose pas encore.",
      therapies_lede: "Une bibliothèque vivante des protocoles que nous avons testés, étudiés, ou suivis pour Marc et les enfants de l'association.",
      therapies_foot: "12 protocoles documentés · plus de 40 études compilées",
      therapies_link: "Accéder à la bibliothèque complète",
      news_eyebrow: "Actualités",
      news_title: "Ce qui s'est passé récemment.",
      news_readmore: "Lire l'article",
      join_eyebrow: "Adhésion · 30€/an",
      join_title: "Devenir membre, c'est rejoindre une famille.",
      join_body: "Accès à une page privée avec contacts cliniciens, prix négociés, hébergements, localisations des centres. Toutes les ressources que Svetlana a négociées pour les enfants de l'association.",
      join_perks: [
        "Contacts directs des cliniciens et chercheurs",
        "Prix négociés sur les stages et matériels",
        "Conférences Zoom mensuelles avec les inventeurs",
        "Accompagnement personnalisé pour vos voyages thérapeutiques"
      ],
      join_cta: "Adhérer · 30€/an",
      donate_title: "Ou faire un don, simplement.",
      donate_body: "Chaque euro nous permet d'inviter un thérapeute, de financer un stage pour un enfant qui n'en a pas les moyens, de continuer à chercher.",
      donate_cta: "Faire un don",
      contact_title: "Nous écrire",
      address: "138 Grande Rue, 38700 La Tronche, France",
      footer_follow: "Suivre",
      footer_act: "Agir",
      footer_member: "Adhérer",
      footer_partners: "Présentation partenaires (PDF)",
      footer_tag: "Ma Rééducation Collective — Association loi 1901",
      footer_copy: "© 2023–2026 Ma Rééducation Collective",
      footer_love: "Site refondu avec amour · pour Marc et tous les enfants"
    },
    en: {
      nav: [
        { label: "Mission", href: "#mission" },
        { label: "Marc", href: "#marc" },
        { label: "Therapies", href: "#therapies" },
        { label: "News", href: "#news" },
        { label: "Membership", href: "#join" }
      ],
      donate: "Donate",
      eyebrow_hero: "French nonprofit · Since 2023",
      hero_kicker: "My Collective",
      hero_title: "Rehabilitation.",
      hero_lede: "Giving children with brain injuries — like Marc — access to the most innovative rehabilitation protocols in the world.",
      hero_meta: ["10 countries visited", "27 protocols documented", "1 mother who won't give up"],
      cta_primary: "Support Marc",
      cta_secondary: "Read his story",
      portrait_name: "Marc, age 14",
      portrait_role: "Survivor, son, future YouTuber",
      stat_unit: "min",
      stat_lbl: "The time before his heart restarted. Our whole story begins there.",
      mission_eyebrow: "Our mission",
      mission_title: "No parent should have to search alone.",
      mission_body: "When Marc had a cardiac arrest at age 4, his mother traveled the world — Spain, Poland, Israel, Russia, USA — to find therapies that don't yet exist in France. Today, the association shares those resources, negotiates intensive programs, organizes conferences with researchers and clinicians, and walks alongside other families on the same path.",
      pillars: [
        { n: "01", t: "Research & monitoring", d: "A living map of neuro-rehab therapies around the world — neuromodulation, stem cells, hyperbaric oxygen, SPML, photobiomodulation." },
        { n: "02", t: "Intensive programs", d: "Organizing rehab stays in our premises or in partnership with clinics abroad, at negotiated rates." },
        { n: "03", t: "Conferences", d: "Live Zoom and YouTube channel with the inventors and researchers: Yuri Danilov, BE Alink, Marco Gostoli, Manny Medina." }
      ],
      story_eyebrow: "Marc's story",
      story_title: "On January 9, 2016, Marc collapsed on a playground.",
      story_lede: "He was 4. He was found fifteen to twenty minutes later. His parents, bystanders, soldiers from the Sentinelle force, and firefighters performed CPR until his heart restarted.",
      story_chapters: [
        { y: "2016", t: "The arrest", d: "Grenoble University Hospital. Resuscitation, ICU, rehabilitation ward. Hospitalized until May." },
        { y: "2016–2019", t: "The heart", d: "Five cardiac surgeries to treat Wolff-Parkinson-White syndrome. The last one in Milan." },
        { y: "2017→", t: "Around the world", d: "Spain, Poland, Germany, Bulgaria, Israel, Russia, USA. In every country, a protocol." },
        { y: "Today", t: "6th grade ULIS", d: "Marc is in 6th grade with a learning aide. He wants to be a YouTuber. He met FuzeIII in April 2026." }
      ],
      story_pull: "“The day you were born, the world became more colorful and kinder.”",
      story_pull_attr: "— his mother, on his birthday",
      story_photo_cap: "A mother, her son — where everything began.",
      book_title: "Marc<br>the Invincible",
      book_author: "Svetlana Serigny",
      book_eyebrow: "The book",
      book_h: "His story, told by his mother.",
      book_body: "Battles, doubts, perseverance — the testimony of an unconditional love. Available in French and English, paper and digital.",
      therapies_eyebrow: "Documented therapies",
      therapies_title: "What France doesn't yet offer.",
      therapies_lede: "A living library of the protocols we've tested, studied, or followed for Marc and the children of the association.",
      therapies_foot: "12 protocols documented · 40+ studies compiled",
      therapies_link: "Access the full library",
      news_eyebrow: "News",
      news_title: "What's happened recently.",
      news_readmore: "Read the article",
      join_eyebrow: "Membership · €30/year",
      join_title: "Becoming a member is joining a family.",
      join_body: "Access to a private page with clinician contacts, negotiated prices, accommodation, center locations. All the resources Svetlana has negotiated for the association's children.",
      join_perks: [
        "Direct contacts of clinicians and researchers",
        "Negotiated prices on programs and equipment",
        "Monthly Zoom conferences with the inventors",
        "Personalized support for your therapeutic trips"
      ],
      join_cta: "Join · €30/year",
      donate_title: "Or simply make a donation.",
      donate_body: "Every euro lets us invite a therapist, fund a program for a child whose family can't afford it, keep searching.",
      donate_cta: "Donate",
      contact_title: "Get in touch",
      address: "138 Grande Rue, 38700 La Tronche, France",
      footer_follow: "Follow",
      footer_act: "Take action",
      footer_member: "Become a member",
      footer_partners: "Partners deck (PDF)",
      footer_tag: "Ma Rééducation Collective — French nonprofit",
      footer_copy: "© 2023–2026 Ma Rééducation Collective",
      footer_love: "Site rebuilt with love · for Marc and every child"
    }
  },

  therapies: [
    { abbr: "TLNS", name: "Translingual Neurostimulation", origin: "Russia / USA",   tag: "neuromodulation", years: "2018→" },
    { abbr: "HBOT", name: "Hyperbaric Oxygen Therapy",     origin: "Israel",         tag: "oxygen",          years: "2017" },
    { abbr: "STEM", name: "Stem cells (HLA-matched cord blood)", origin: "Russia · Duke USA", tag: "biological", years: "2018, 2020" },
    { abbr: "SPML", name: "Selective Percutaneous Myofascial Lengthening", origin: "Dr. Roy Nuzzo · NJ, USA", tag: "surgical", years: "2022, 2024" },
    { abbr: "DMI",  name: "Dynamic Movement Intervention", origin: "Spain",          tag: "motor",           years: "ongoing" },
    { abbr: "GYRO", name: "GyroStim — passive vestibular stimulation", origin: "Bulgaria", tag: "vestibular", years: "2019" },
    { abbr: "LLLT", name: "Low Level Light Therapy / Photobiomodulation", origin: "Italy — Cerebro", tag: "neuromodulation", years: "2023→" },
    { abbr: "SCS",  name: "Non-invasive spinal cord stimulation", origin: "Chattanooga · USA", tag: "neuromodulation", years: "2023" },
    { abbr: "EMS",  name: "Exopulse Mollii Suit (clinical trial)", origin: "France · Nice Rossetti", tag: "motor", years: "2024" },
    { abbr: "TOM",  name: "Tomatis",                       origin: "France",         tag: "auditory",        years: "ongoing" },
    { abbr: "FELD", name: "Feldenkrais / ABM",             origin: "International",  tag: "motor",           years: "ongoing" },
    { abbr: "ALK",  name: "Alinker walking-bike (daily)",  origin: "BE Alink · Netherlands", tag: "mobility", years: "daily" }
  ],

  // Used only if articles/index.json fails to load.
  newsFallback: []
};
