<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>marc·asso — Ma Rééducation Collective</title>

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,300;9..144,400;9..144,500;9..144,600&family=Inter+Tight:wght@400;500;600;700&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="<?php echo get_template_directory_uri(); ?>/style.css">
  <link rel="stylesheet" href="<?php echo get_template_directory_uri(); ?>/assets/css/page.css">
</head>
<body data-screen-label="Homepage">

  <!-- Page is composed from one mount point per section.
       Each section's HTML is generated by its own JS module under js/sections/.
       Articles live in articles/ and are listed in articles/index.json. -->

  <div id="app-header"></div>
  <main>
    <div id="app-hero"></div>
    <div id="app-mission"></div>
    <div id="app-story"></div>
    <div id="app-therapies"></div>
    <div id="app-news"></div>
    <div id="app-join"></div>
  </main>
  <div id="app-footer"></div>

  <!-- Data + utils -->
  <script src="<?php echo get_template_directory_uri(); ?>/assets/js/utils.js"></script>
  <script src="<?php echo get_template_directory_uri(); ?>/assets/js/data.js"></script>
  <script src="<?php echo get_template_directory_uri(); ?>/assets/js/articles-index.js"></script>

  <!-- Sections — one file each -->
  <script src="<?php echo get_template_directory_uri(); ?>/assets/js/sections/header.js"></script>
  <script src="<?php echo get_template_directory_uri(); ?>/assets/js/sections/hero.js"></script>
  <script src="<?php echo get_template_directory_uri(); ?>/assets/js/sections/mission.js"></script>
  <script src="<?php echo get_template_directory_uri(); ?>/assets/js/sections/story.js"></script>
  <script src="<?php echo get_template_directory_uri(); ?>/assets/js/sections/therapies.js"></script>
  <script src="<?php echo get_template_directory_uri(); ?>/assets/js/sections/news.js"></script>
  <script src="<?php echo get_template_directory_uri(); ?>/assets/js/sections/join.js"></script>
  <script src="<?php echo get_template_directory_uri(); ?>/assets/js/sections/footer.js"></script>

  <!-- Boot -->
  <script src="<?php echo get_template_directory_uri(); ?>/assets/js/app.js"></script>
</body>
</html>
