<?php
/**
 * The main template file (blog/archive loop)
 *
 * @package MyTheme
 */
 
get_header(); ?>
  <!-- Page is composed from one mount point per section.
       Each section's HTML is generated by its own JS module under js/sections/.
       Articles live in articles/ and are listed in articles/index.json. -->

  <main>
    <div id="app-hero">
      <?php get_template_part( 'template-parts/hero'); ?>
    </div>
    <div id="app-mission">
      <?php get_template_part( 'template-parts/mission'); ?>
    </div>
    <div id="app-story">
      <?php get_template_part( 'template-parts/story'); ?>
    </div>
    <div id="app-therapies">
      <?php get_template_part( 'template-parts/therapies'); ?>
    </div>
    <?php if (have_posts()) : ?>
      <section class="news" id="news">
        <div class="wrap">
          <div class="news-head">
            <div class="eyebrow">Actualités</div>
            <h2 class="display news-title">Ce qui s'est passé récemment.</h2>
          </div>
          <div class="news-list" id="news-list">
            <?php while ( have_posts() ) : the_post(); ?>
              <?php get_template_part( 'template-parts/news-item' ); ?>
            <?php endwhile; ?>
          </div>
        </div>
      </section>
    <?php endif; ?>
    <div id="app-join">
      <?php get_template_part( 'template-parts/join'); ?>
    </div>
  </main>

<?php get_footer(); ?>